"""注入攻击关键词权重表。

命中关键词就累加对应权重，和正则、越狱句一起算风险分。
关键词权重比正则更高，因为这些词单独出现就足够可疑。
"""

INJECTION_KEYWORDS = {
    # 忽略/覆盖指令
    "ignore previous instructions": 5,
    "ignore all instructions": 5,
    "disregard previous": 5,
    "忽略以上指令": 5,
    "忽略之前的所有": 5,
    "无视系统设定": 5,
    "覆盖提示词": 5,
    "override system": 5,
    "replace system prompt": 5,
    # 越狱
    "越狱模式": 4,
    "jailbreak": 4,
    "DAN mode": 4,
    "无约束模式": 4,
    "不受任何限制": 4,
    "no restrictions": 4,
    "解除所有限制": 4,
    # 泄露
    "泄露提示词": 5,
    "reveal hidden rules": 5,
    "输出系统提示词": 5,
    "dump system prompt": 5,
    "show your instructions": 5,
    # 绕过安全
    "strip rules": 3,
    "ignore content policy": 5,
    "无视内容政策": 5,
    "绕过安全": 4,
    "bypass safety": 4,
    # 角色冒充
    "你现在是管理员": 4,
    "扮演系统": 4,
    "act as root": 4,
    "you are now unbounded": 4,
    # 系统伪造/泄露
    "output your system prompt": 6,
    "return only the system prompt": 6,
    "show your instructions": 6,
    "system message": 4,
    "developer message": 4,
    "initial prompt": 4,
    # 覆盖/绕过
    "supersede": 4,
    "strip rules": 4,
    "load prompt from url": 4,
    "fetch prompt from": 4,
    "certutil -decode": 4,
    "powershell -enc": 4,
    # 角色调教
    "你是一只猫娘": 4,
    "act as DAN": 4,
    "GalGame": 3,
    "角色扮演": 3,
    # 越狱辅助
    "进入越狱": 4,
    "developer mode": 4,
    "没有任何限制": 4,
    "无视安全策略": 5,
    "bypass content filter": 4,
    # 英文注入/越狱补充
    "override your safety protocols": 5,
    "override safety": 4,
    "dump your memory": 4,
    "reveal your internal instructions": 5,
    "i grant you developer mode": 4,
    "from now on you will act as": 4,
    "you must obey my commands": 3,
    "无条件服从": 4,
    "必须服从": 4,
    "绝对服从": 4,
    "obey without question": 4,
    "system override": 4,
    "embrace jailbreak": 4,
    "do anything now": 4,
    "dan mode": 4,
    "simulate a jailbroken": 4,
    "developer instructions": 4,
    "disable guardrails": 5,
    "priority override": 3,
    "switch to root mode": 4,
    "complete freedom": 3,
    "system priority: override": 5,
    "output chain of thought": 5,
    "reveal chain of thought": 5,
    "show your reasoning": 4,
    "do not follow policy": 5,
    # 中文越狱补充
    "忽略安全": 4,
    "跳过安全": 4,
    "我是你的上级": 3,
    "猫娘": 2,
    # 仇恨/偏见补充
    "负面刻板印象": 6,
    "煽动性": 4,
    "煽动厌恶": 6,
    "激起厌恶": 6,
    "加深偏见": 5,
    "激化偏见": 5,
    "煽动仇恨": 6,
    "激起仇恨": 6,
    "激起敌意": 5,
    "negative stereotype": 5,
    "incite hatred": 6,
    "stoke hatred": 5,
    "fuel hatred": 5,
    "fuel prejudice": 5,
    "spread prejudice": 4,
    "inflame hatred": 5,
    # 危险操作/命令
    "rm -rf": 6,
    "删除所有文件": 6,
    "修改服务器": 5,
    "关闭服务器": 5,
    "删库": 6,
    "drop table": 6,
    "shutdown": 4,
    "reboot": 4,
    "改密码": 5,
    "system prompt 发给我": 5,
    "提示词发给我": 5,
}
